{% set name = "requests-cache" %}
{% set version = "0.7.1" %}
{% set hash_val = "1e88c6bc7037df2a0f06377c7420aa60450abc8ac11c760bc562a6e50482e364" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - poetry
    - pip

  run:
    - python >=3.6
    - attrs >=21.2
    - cattrs >=1.7
    - itsdangerous >=2.0.1
    - pyyaml >=5.4
    - requests >=2.17
    - url-normalize >=1.4

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.models
    - requests_cache.serializers

about:
  home: https://github.com/reclosedev/requests-cache/
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: A transparent, persistent cache for python requests
  dev_url: https://github.com/reclosedev/requests-cache/
  doc_url: https://requests-cache.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jwcook
    - cj-wright
