{% set name = "requests-cache" %}
{% set version = "0.6.3" %}
{% set hash_val = "0b9b5555b3b2ecda74a9aa5abd98174bc7332de2e1d32f9f8f056583b01d6e99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - requests >=2.0
    - itsdangerous
    - url-normalize

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - requests_cache
    - requests_cache.backends

about:
  home: https://github.com/reclosedev/requests-cache/
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: A transparent, persistent cache for python requests
  dev_url: https://github.com/reclosedev/requests-cache/
  doc_url: https://requests-cache.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jwcook
