{% set name = "requests-cache" %}
{% set version = "0.9.0" %}
{% set hash_val = "d82b3af855ffc16807a401cfe5a924957a083512b430e635045cee767b99d169" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - poetry
    - pip

  run:
    - python >=3.7
    - appdirs >=1.4.4
    - attrs >=21.2
    - cattrs >=1.8
    - itsdangerous >=2.0
    - pyyaml >=5.4
    - requests >=2.17
    - url-normalize >=1.4
    - urllib3 >=1.25.5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.models
    - requests_cache.serializers

about:
  home: https://github.com/reclosedev/requests-cache/
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: A transparent, persistent cache for python requests
  dev_url: https://github.com/reclosedev/requests-cache/
  doc_url: https://requests-cache.readthedocs.io/

extra:
  recipe-maintainers:
    - jwcook
    - cj-wright
