{% set name = "requests-cache" %}
{% set version = "0.9.5" %}
{% set hash_val = "bd67575f541f9c10f44f8b49d8d449fb55db8af2e27d93c56349f227b78e4b70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - poetry
    - pip

  run:
    - python >=3.7
    - appdirs >=1.4.4
    - attrs <22.0,>=21.2
    # cattrs 22.1+ depends on exceptiongroup, which doesn't have a stable release on conda-forge
    - cattrs <22.1,>=1.8.1
    - itsdangerous >=2.0
    - pyyaml >=5.4
    - requests >=2.22
    - url-normalize >=1.4
    - urllib3 >=1.25.5

test:
  requires:
    - pip
  # Disabling check against PyPI dependencies until conda dependencies can be updated to match
  # commands:
  #   - pip check
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.models
    - requests_cache.serializers

about:
  home: https://github.com/requests-cache/requests-cache/
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: A transparent, persistent cache for python requests
  dev_url: https://github.com/requests-cache/requests-cache/
  doc_url: https://requests-cache.readthedocs.io/

extra:
  recipe-maintainers:
    - jwcook
    - cj-wright
