{% set name = "requests-cache" %}
{% set version = "1.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 68abc986fdc5b8d0911318fbb5f7c80eebcd4d01bfacc6685ecf8876052511d1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - python
    - requests >=2.22
    - urllib3 >=1.25.5
    - attrs >=21.2
    - cattrs >=22.2
    - platformdirs >=2.5
    - url-normalize >=1.4
  run_constrained:
    # Optional backend dependencies
    - boto3 >=1.15
    - botocore >=1.18
    - pymongo >=3
    - redis >=3
    # Optional serialization dependencies
    - bson >=0.5
    - itsdangerous >=2.0
    - pyyaml >=6.0.1
    - ujson >=5.4

# Unable to run tests: 
# Module not found "timeout-decorator" -> https://pypi.org/project/timed-decorator (pkg is not in the main channel)
test:
  imports:
    - requests_cache
    - requests_cache.backends
    - requests_cache.models
    - requests_cache.serializers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/requests-cache/requests-cache
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  summary: A transparent persistent cache for the requests library
  description: |
    requests-cache is a persistent HTTP cache that provides an easy way to get better performance with the python requests library.
  dev_url: https://github.com/requests-cache/requests-cache
  doc_url: https://requests-cache.readthedocs.io

extra:
  recipe-maintainers:
    - jwcook
    - cj-wright
