travis:
  secure:
    BINSTAR_TOKEN: cngTP77J3D4fD5IU189AnkHCP0GBciht/SVqtFoA5nAEhWQB+mxBaH4GjRegeSMZ5dapG6D7OKr16aMgmhjVLGEE/hVwfIbQbiUyc83UnPxF3RfRt9EgGjj4d0rRhEWvk4shgb71MvOKf51gqQ2L/1u0K1IDDyhu+3kFhyXT6256YcTCjm4sNXLVm8y+9Ahfk507G8l+T2zP5sL5fAd1fVCqrWNiGGjTWT2ktgxUKl4vaS5awoqHQ53Kev/hTJnwZVi4t7phkSibRvM1AStR94MQ6tgmIgnIndOsLob/Lx+vBpX5mgADlVyjoatm0je+XNOkHJqfMHUaT3R/g9q+SSthY/k8rOloMFnf8ToLFpBuayxmgHKqXLoVf1tZX3uqj3ATM0pcsAhnzu15O/ekWOmt8ws96Ba7kfNnH5HXitI77W+zXFS5rfVCGI1yGiUcPEl1StPsMv+qIhH06cCO1rsIafmIAIOU2kpqoASlPzRMrCnMaBssljZqpVUaOnAWiPmt3B6WhQkj8ioSW4WDh2HWLhRLzV/rwSdtarkV7VfYrGm3crsGqaFwmFeLtXmq8ecvvmhbqtLztET+iH2XcS6rMF6i/77HCERnOEpsAJs7op8OEf+GBey1x+siNtHLaVgdeb/AWxGqhuaHXQnwEN7eA6wqom4EqSeecP0MWbg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
