travis:
  secure:
    BINSTAR_TOKEN: ighTyCrOhXLRZJq+lFoVrOUKhnBip+CiNjKRuNzRZNPHGVCvSv8lM1hHOxeptA2XTkInsqdoB3Ju0idvhux2awqF9invg2uckVC/2oiLUbviPSqIAzHBCA8ZqnR2lGSPTdQg/Pqd8rTHSDWt8t9R7EEUGT4p7lKltz9mFjad/VN5nQ7IBeBFnc6KEt/s1WABSIVWHJ67xKevWK1vU3SRnQQ6sx3o1j87H+BXUNFyTM1J8ozLQEGTBoQ1XdzhleVQIediIb91dkbid8hGRBdrOWySt/ZYezxAw6R1O2TW8RiaRsWn1dA4OEMsRL5Ff2E8G/fgO4PcQKioBIXiHCFX5PnDPJmFK7jsJYhTEs7Ozg53VvO4pD9hKholVg5MTP8o3LZKB610N2+bA91DQkmSaCDQ0mYPhBVbflkNNQq/0MHsvvLkeltpSlmIERgsqbAnZw6CPxfYTCCu/ad0jDzjeWCgncwJjeVVwCyzdcF345Zy33ziPdFVG8NYgWe5N+966x+gSgmW3B5VQXL3A1AqkG9vd4iEmjqe7exTDp+lziG5Q3BNkeaU88i8Q0vyLxxJVE092W/X/VJpPv6mFMwQ1jD91ZH0my9ZVS3RKkVLUNc+4yeQdlcjqiFEPGZh+jFnA8QvFVYrssrC5i0kC8J/TA0HsIBDHUtqCHKtRxAEGF4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
